deployment:
  tasks:
    - export DEPLOYPATH=/home4/georgiyo/public_html/
    - /bin/rsync -av --delete \
      --exclude='.git' \
      --exclude='.env' \
      --exclude='.cpanel.yml' \
      --exclude='assets/img/portfolio/video' \
      ./ $DEPLOYPATH